apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube-mcp
  labels:
    name: sonarqube-mcp
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sonarqube-mcp-quota
  namespace: sonarqube-mcp
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sonarqube-mcp-limits
  namespace: sonarqube-mcp
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container