apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-mcp-secrets
  namespace: sonarqube-mcp
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  postgres-password: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  redis-password: cmVkaXNfcGFzc3dvcmQ=  # redis_password
  sonarqube-token: c29uYXJxdWJlX3Rva2Vu  # sonarqube_token
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: sonarqube-mcp
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key
  tls.crt: LS0tLS1CRUdJTi...  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi...  # Base64 encoded private key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-mcp-config
  namespace: sonarqube-mcp
data:
  POSTGRES_DB: "sonarqube"
  POSTGRES_USER: "sonarqube"
  SONARQUBE_URL: "http://sonarqube-service:9000/sonarqube"
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@redis-service:6379/0"
  CACHE_TTL: "300"
  LOG_LEVEL: "INFO"
  SERVER_DEBUG: "false"
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"