# Infrastructure services for SonarQube MCP
version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: sonarqube-nginx
    restart: unless-stopped
    depends_on:
      - sonarqube
      - streamlit-app
      - mcp-server
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_ssl:/etc/nginx/ssl
      - ../../../logs/nginx:/var/log/nginx
    networks:
      - sonarqube-mcp
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: ${NGINX_MEMORY_LIMIT:-128M}
        reservations:
          memory: 64M